import assert from 'node:assert/strict';
import {writeFile,mkdir} from 'node:fs/promises';
import {initialWorkspace} from '../lib/model.ts';
import {relatedResources} from '../lib/resource-model.ts';
import {createVault,unlockVault,seal,unseal,generatePassword,fromBase64,toBase64} from '../lib/vault-crypto.ts';
const base='http://localhost:5173',cookie={Cookie:'__sites_local_auth=1'},ids=[],folderIds=[],blueprintIds=[];
async function api(path='/api/workspace',input,other=false,extra={}){const r=await fetch(base+path,{method:input?'POST':'GET',headers:{...(other?{}:cookie),...(input?{'Content-Type':'application/json'}:{}),...extra},body:input?JSON.stringify(input):undefined});const raw=await r.text();let data;try{data=JSON.parse(raw)}catch{data={error:raw}}return {status:r.status,data};}
function resource(fields={}){return {type:'resource-save',id:crypto.randomUUID(),kind:'asset',source:'link',title:'[Verification] Resource',url:'https://example.com/reference',description:'A useful reference',owner:'me',targets:[],shared:false,...fields}}
const credentials={username:'test@example.invalid',password:'synthetic-test-secret-do-not-use',url:'https://example.com',notes:'Synthetic test only'};
const master='Synthetic verification master only 2026';
let configCreated=false,configId='';
try{
 const pure=initialWorkspace();pure.resources=['client','project','task','other','global','blueprint'].map(id=>({id,title:id,shared:id==='global'?1:0,archived:0}));pure.blueprints=[{id:'flow',projectId:'autumn',spaceId:null}];pure.resourceLinks=[['client','space','nord'],['project','project','autumn'],['task','task','t1'],['other','task','t2'],['blueprint','blueprint','flow']].map(([resourceId,targetType,targetId])=>({resourceId,targetType,targetId}));
 assert.deepEqual(new Set(relatedResources(pure,{type:'task',id:'t1'}).map(r=>r.id)),new Set(['client','project','task','global','blueprint']));
 assert.equal(relatedResources(pure,{type:'space',id:'nord'}).length,6);assert.equal(relatedResources(pure,{type:'project',id:'autumn'}).length,6);assert(!relatedResources(pure,{type:'space',id:'harbor'}).some(r=>r.id==='client'));
 const crypt=await createVault(master);assert.equal(crypt.key.extractable,false);const sealed=await seal(crypt.key,crypt.config.id,'record',credentials),sealed2=await seal(crypt.key,crypt.config.id,'record',credentials);assert.notEqual(sealed.iv,sealed2.iv);assert.deepEqual(await unseal(crypt.key,crypt.config.id,'record',sealed),credentials);
 await assert.rejects(()=>unlockVault('wrong master passphrase',crypt.config));await assert.rejects(()=>unseal(crypt.key,crypt.config.id,'other-record',sealed));await assert.rejects(()=>unseal(crypt.key,'other-vault','record',sealed));const tamper=fromBase64(sealed.ciphertext);tamper[0]^=1;await assert.rejects(()=>unseal(crypt.key,crypt.config.id,'record',{...sealed,ciphertext:toBase64(tamper)}));assert.equal(generatePassword().length,24);
 let result=await api();assert.equal(result.status,200,JSON.stringify(result.data));assert(result.data.resources.some(r=>r.id==='starter-call'));assert(result.data.resources.every(r=>!('fileKey' in r)&&!('sealed' in r)));
 result=await api('/api/workspace',{type:'folder-create',name:'[Verification] Folder'});assert.equal(result.status,200);const folder=result.data.folders.find(f=>f.name==='[Verification] Folder');folderIds.push(folder.id);
 const draft=resource({folderId:folder.id,targets:[{type:'project',id:'autumn'},{type:'task',id:'t1'}]});ids.push(draft.id);result=await api('/api/workspace',draft);assert.equal(result.status,200,JSON.stringify(result.data));let saved=result.data.resources.find(r=>r.id===draft.id);assert.equal(saved.folderId,folder.id);assert.equal(result.data.resourceLinks.filter(l=>l.resourceId===saved.id).length,2);
 result=await api('/api/workspace',{...draft,revision:saved.revision,title:'[Verification] Updated'});assert.equal(result.status,200);assert.equal((await api('/api/workspace',{...draft,revision:saved.revision})).status,409);assert.equal((await api('/api/workspace',{...draft,revision:1},true)).status,404);
 assert.equal((await api('/api/workspace',resource({url:'javascript:alert(1)'}))).status,400);assert.equal((await api('/api/workspace',resource({url:'https://name:password@example.com'}))).status,400);assert.equal((await api('/api/workspace',resource({targets:[{type:'project',id:'nonexistent'}]}))).status,404);assert.equal((await api('/api/workspace',resource(),false,{Origin:'https://another-origin.invalid'})).status,403);
 result=await api('/api/workspace',{type:'blueprint-create',name:'[Verification] Flow',description:'Form → SMS → booked',projectId:'autumn'});assert.equal(result.status,200);blueprintIds.push(result.data.blueprints.find(b=>b.name==='[Verification] Flow').id);
 const text=resource({kind:'template',source:'text',content:'Hello [client], here is the plan.',category:'Call scripts',url:'',targets:[{type:'blueprint',id:blueprintIds[0]}]});ids.push(text.id);result=await api('/api/workspace',text);assert.equal(result.status,200);assert(relatedResources(result.data,{type:'project',id:'autumn'}).some(r=>r.id===text.id));
 const form=new FormData();form.set('file',new File(['<!doctype html><html><body><h1>Test tool</h1></body></html>'],'verification-tool.html',{type:'text/html'}));form.set('kind','tool');form.set('targets',JSON.stringify([{type:'project',id:'autumn'}]));let response=await fetch(base+'/api/files',{method:'POST',headers:cookie,body:form});let uploaded=await response.json();assert.equal(response.status,200,JSON.stringify(uploaded));const file=uploaded.resources.find(r=>r.filename==='verification-tool.html');ids.push(file.id);assert.equal(file.source,'html');assert(!('fileKey' in file));
 response=await fetch(base+`/api/files?id=${file.id}`,{headers:cookie});assert.equal(response.status,200);assert.match(response.headers.get('Content-Disposition'),/^attachment/);assert.match(response.headers.get('Content-Security-Policy'),/sandbox/);assert.match(await response.text(),/Test tool/);
 response=await fetch(base+`/api/files?id=${file.id}&run=1`,{headers:cookie});assert.equal(response.status,200);assert.match(response.headers.get('Content-Security-Policy'),/sandbox allow-scripts allow-forms allow-downloads/);assert(!response.headers.get('Content-Security-Policy').includes('allow-same-origin'));
 assert.equal((await fetch(base+`/api/files?id=${file.id}`)).status,404);
 const badForm=new FormData();badForm.set('file',new File(['not html'],'tool.js'));badForm.set('kind','tool');assert.equal((await fetch(base+'/api/files',{method:'POST',headers:cookie,body:badForm})).status,400);
 const largeForm=new FormData();largeForm.set('file',new File([new Uint8Array(20*1024*1024+1)],'too-large.bin'));assert.equal((await fetch(base+'/api/files',{method:'POST',headers:cookie,body:largeForm})).status,413);
 result=await api('/api/vault');assert.equal(result.status,200);assert.equal(result.data.config,null,'Do not overwrite a real vault; tests require an unset local sample vault.');result=await api('/api/vault',crypt.config);assert.equal(result.status,200,JSON.stringify(result.data));configCreated=true;configId=crypt.config.id;assert.equal((await api('/api/vault',crypt.config)).status,409);
 const loginId=crypto.randomUUID(),encrypted=await seal(crypt.key,crypt.config.id,loginId,credentials),login=resource({id:loginId,kind:'vault',source:'vault',title:'[Verification] Encrypted login',url:'',sealed:encrypted,targets:[{type:'space',id:'nord'}]});ids.push(login.id);result=await api('/api/workspace',login);assert.equal(result.status,200,JSON.stringify(result.data));const workspaceText=JSON.stringify(result.data);assert(!workspaceText.includes(credentials.password));assert(!workspaceText.includes(credentials.username));assert(!workspaceText.includes(encrypted.ciphertext));
 result=await api('/api/vault?id='+login.id);assert.equal(result.status,200);assert.deepEqual(await unseal(crypt.key,crypt.config.id,login.id,result.data.sealed),credentials);assert.equal((await api('/api/vault?id='+login.id,undefined,true)).status,404);
 const wrong=resource({kind:'vault',source:'vault',sealed:{version:1,iv:'bad',ciphertext:'plaintext'}});assert.equal((await api('/api/workspace',wrong)).status,400);
 const latest=(await api()).data.resources.find(r=>r.id===draft.id);result=await api('/api/workspace',{type:'resource-archive',id:latest.id,revision:latest.revision,archived:true});assert.equal(result.status,200);assert(!relatedResources(result.data,{type:'project',id:'autumn'}).some(r=>r.id===latest.id));result=await api('/api/workspace',{type:'resource-archive',id:latest.id,revision:latest.revision+1,archived:false});assert.equal(result.status,200);
 console.log('PASS: inherited links and deduplication, folders, editable templates, blueprint connections, optimistic concurrency, tenant isolation, safe URL validation, R2 upload/download and HTML sandbox, file size limits, encrypted vault persistence, wrong key/tamper rejection, unique IVs, no secret leakage, archive/restore.');
}finally{
 for(const id of [...ids,...folderIds,...blueprintIds])assert.match(id,/^[0-9a-f-]{36}$/);
 const sql=[...ids.flatMap(id=>['resourceLinks','vaultEntries','resources'].map(table=>`DELETE FROM ${table} WHERE org='local_seedy' AND ${table==='resourceLinks'?'resourceId':'id'}='${id}';`)),...folderIds.map(id=>`DELETE FROM folders WHERE org='local_seedy' AND id='${id}';`),...blueprintIds.map(id=>`DELETE FROM blueprints WHERE org='local_seedy' AND id='${id}';`),...(configCreated?[`DELETE FROM vaultConfig WHERE org='local_seedy' AND id='${configId}';`]:[])];await mkdir('work',{recursive:true});await writeFile('work/resource-cleanup.sql',sql.join('\n'));
}
