'use client';
import ClientFocus from './client-focus';
import { useState, useEffect, useCallback, type CSSProperties, type FormEvent } from 'react';
import { Sun, Layers, BriefcaseBusiness, Workflow, Blocks, ChartNoAxesCombined, Building2, Search, Bell, Plus, ChevronRight, ArrowUpRight, Check, Circle, CircleDot, CircleCheck, MessageSquare, ArrowRight, Clock3, ExternalLink, FileText, Inbox, Users, LoaderCircle } from 'lucide-react';
import { Sidebar, SidebarProvider, SidebarHeader, SidebarContent, SidebarFooter, SidebarGroup, SidebarGroupLabel, SidebarMenu, SidebarMenuItem, SidebarMenuButton, SidebarTrigger } from '@/components/ui/sidebar';
import { Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription } from '@/components/ui/sheet';
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription } from '@/components/ui/dialog';
import { Tabs, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Select, SelectTrigger, SelectValue, SelectContent, SelectItem } from '@/components/ui/select';
import { CommandDialog, CommandInput, CommandList, CommandEmpty, CommandGroup, CommandItem } from '@/components/ui/command';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { stages, initialWorkspace, type Workspace, type Task, type Member, type Stage } from '@/lib/model';

const navigation = [{id:'day',name:'My day',icon:Sun},{id:'work',name:'Work',icon:Layers},{id:'spaces',name:'Spaces',icon:BriefcaseBusiness},{id:'blueprints',name:'Blueprints',icon:Workflow},{id:'tools',name:'Tools',icon:Blocks},{id:'insights',name:'Insights',icon:ChartNoAxesCombined},{id:'organization',name:'Organization',icon:Building2}];
function Avatar({member,small=false}:{member?:Member;small?:boolean}) { return <span className={`avatar ${small?'small':''}`} style={{'--member-color':member?.color||'#778291'} as CSSProperties} aria-label={member?.name}>{member?.name.slice(0,2)||'?'}</span> }
function Picker({label,value,items,onChange}:{label:string;value:string;items:{value:string;label:string}[];onChange:(v:string)=>void}) {return <Select value={value} onValueChange={v=>v&&onChange(v)}><SelectTrigger aria-label={label} className="field-picker"><SelectValue>{items.find(i=>i.value===value)?.label||value}</SelectValue></SelectTrigger><SelectContent>{items.map(i=><SelectItem key={i.value} value={i.value}>{i.label}</SelectItem>)}</SelectContent></Select>}
const stageIcon = [Circle,CircleDot,Clock3,CircleCheck];
export default function Studio() {
 const [data,setData]=useState<Workspace>(initialWorkspace),[ready,setReady]=useState(false),[page,setPage]=useState('day'),[scope,setScope]=useState('mine'),[selected,setSelected]=useState<string|null>(null),[spaceId,setSpaceId]=useState<string|null>(null),[projectId,setProjectId]=useState<string|null>(null),[create,setCreate]=useState(false),[search,setSearch]=useState(false),[notices,setNotices]=useState(false),[documentId,setDocumentId]=useState<string|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[needsSignIn,setNeedsSignIn]=useState(false);
 const refresh=useCallback(async()=>{const r=await fetch('/api/workspace');if(r.status===401){setNeedsSignIn(true);return}const body=await r.json() as Workspace & {error?:string};if(!r.ok)throw new Error(body.error||'Unable to load the workspace.');setData(body);setReady(true);setNeedsSignIn(false)},[]);
 useEffect(()=>{refresh().catch(e=>setError(e.message))},[refresh]);
 useEffect(()=>{const timer=setInterval(()=>{if(!selected&&!busy&&!create)refresh().catch(()=>{})},15000);return()=>clearInterval(timer)},[selected,busy,create,refresh]);
 useEffect(()=>{const onKey=(e:KeyboardEvent)=>{if((e.metaKey||e.ctrlKey)&&e.key==='k'){e.preventDefault();setSearch(true)}};window.addEventListener('keydown',onKey);const params=new URLSearchParams(window.location.search);if(params.get('task'))setSelected(params.get('task'));if(params.get('space')){setPage('spaces');setSpaceId(params.get('space'));}return()=>window.removeEventListener('keydown',onKey)},[]);
 const openTask=(id:string)=>{setSelected(id);const url=new URL(window.location.href);url.searchParams.set('task',id);window.history.replaceState(null,'',url)};
 const closeTask=()=>{setSelected(null);const url=new URL(window.location.href);url.searchParams.delete('task');window.history.replaceState(null,'',url)};
 const act=async(command:Record<string,unknown>)=>{if(busy||!ready)return false;setBusy(true);setError('');try{const r=await fetch('/api/workspace',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(command)});const body=await r.json() as Workspace & {error?:string};if(!r.ok)throw new Error(body.error||'The change could not be saved.');setData(body);setMessage('Saved to your workspace');return true}catch(e){setError(e instanceof Error?e.message:'The change could not be saved.');return false}finally{setBusy(false)}};
 const updateSpaceUrl=(id:string|null)=>{const url=new URL(window.location.href);if(id)url.searchParams.set('space',id);else url.searchParams.delete('space');window.history.replaceState(null,'',url)};
 const navigate=(id:string)=>{updateSpaceUrl(null);setPage(id);setSpaceId(null);setProjectId(null);closeTask();setError('')};
 const space=(id:string)=>{updateSpaceUrl(id);setPage('spaces');setSpaceId(id);setProjectId(null);closeTask()};
 const project=(id:string)=>{updateSpaceUrl(null);setPage('work');setProjectId(id);setSpaceId(null);closeTask()};
 const currentTask=data.tasks.find(t=>t.id===selected), currentSpace=data.spaces.find(s=>s.id===spaceId), currentProject=data.projects.find(p=>p.id===projectId), doc=data.documents.find(d=>d.id===documentId);
 const pending=data.tasks.filter(t=>t.stage==='Review'&&t.reviewer===data.currentMember&&data.reviews.some(r=>r.taskId===t.id&&r.version===t.version&&r.decision==='Pending'));
 const shown=data.tasks.filter(t=>page!=='day'||scope==='team'||t.assignee===data.currentMember).filter(t=>!projectId||t.projectId===projectId).filter(t=>!spaceId||data.projects.find(p=>p.id===t.projectId)?.spaceId===spaceId).sort((a,b)=>a.position-b.position);
 const card=(task:Task)=>{const p=data.projects.find(p=>p.id===task.projectId),s=data.spaces.find(s=>s.id===p?.spaceId),m=data.members.find(m=>m.id===task.assignee);return <button className="task-card" key={task.id} onClick={()=>openTask(task.id)} draggable={ready&&!busy} onDragStart={e=>e.dataTransfer.setData('text/plain',task.id)}><span className="card-context"><span className="brand-dot" style={{background:s?.color||'#919aaa'}}/>{s?.name||'Studio'}</span><strong>{task.title}</strong><span className="card-project">{p?.name||'Inbox'}</span><span className="card-bottom"><Avatar member={m} small/><span>{m?.name}</span><span className="card-note"><MessageSquare size={13}/>{data.notes.filter(n=>n.taskId===task.id).length||''}</span></span></button>};
 const board=<div className="board">{stages.map((stage,i)=>{const Icon=stageIcon[i];return <section key={stage} className="lane" onDragOver={e=>{if(ready)e.preventDefault()}} onDrop={e=>{e.preventDefault();const t=data.tasks.find(t=>t.id===e.dataTransfer.getData('text/plain'));if(t)void act({type:'move',id:t.id,revision:t.revision,stage})}}><h2><Icon size={15} className={`stage-${i}`}/>{stage}<span>{shown.filter(t=>t.stage===stage).length}</span></h2>{shown.filter(t=>t.stage===stage).map(card)}{stage==='Up next'&&<button className="lane-add" onClick={()=>setCreate(true)} disabled={!ready}><Plus size={15}/>Add task</button>}{!shown.some(t=>t.stage===stage)&&<div className="lane-empty">{stage==='Done'?'Finished work will appear here.':'Nothing here yet.'}</div>}</section>})}</div>;
 return <SidebarProvider style={{'--sidebar-width':'218px'} as CSSProperties}><Sidebar className="studio-sidebar"><SidebarHeader className="brand"><span className="brand-symbol"><Layers size={19}/></span><strong>studio</strong><span className="edition">OS</span></SidebarHeader><SidebarContent><SidebarGroup><SidebarGroupLabel>WORKSPACE</SidebarGroupLabel><SidebarMenu>{navigation.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton isActive={page===n.id} onClick={()=>navigate(n.id)} className="nav-item"><n.icon size={18}/><span>{n.name}</span>{n.id==='day'&&<span className="nav-count">{data.tasks.filter(t=>t.assignee===data.currentMember&&t.stage!=='Done').length}</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup><SidebarGroup className="pinned-spaces"><SidebarGroupLabel>YOUR SPACES</SidebarGroupLabel><SidebarMenu>{data.spaces.slice(0,3).map(s=><SidebarMenuItem key={s.id}><SidebarMenuButton onClick={()=>space(s.id)} className="nav-item"><span className="space-initial" style={{color:s.color,background:s.color+'18'}}>{s.name.slice(0,1)}</span><span>{s.name}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarGroup></SidebarContent><SidebarFooter><div className="workspace-state"><span className="status-dot"/>{ready?'Sample workspace':'Connecting…'}<span>PRIVATE</span></div><div className="profile"><Avatar member={data.members.find(m=>m.id===data.currentMember)}/><div><strong>{data.members.find(m=>m.id===data.currentMember)?.name}</strong><small>Workspace owner</small></div></div></SidebarFooter></Sidebar>
 <div className="studio-main"><header className="topbar"><div className="crumb"><SidebarTrigger/><span>Studio workspace</span><ChevronRight size={14}/><strong>{navigation.find(n=>n.id===page)?.name}</strong></div><div className="top-actions"><button className="search-button" onClick={()=>setSearch(true)}><Search size={16}/><span>Search anything</span><kbd>⌘ K</kbd></button><button className="icon-button" aria-label="Notifications" onClick={()=>setNotices(true)}><Bell size={19}/>{data.notices.some(n=>!n.read)&&<span className="notification-dot"/>}</button><Avatar member={data.members[0]} small/></div></header>
 <main className="workspace-content">{!currentSpace&&<div className="page-heading"><div><p className="eyebrow">{new Intl.DateTimeFormat('en',{weekday:'long',month:'long',day:'numeric'}).format(new Date())}</p><h1>{currentProject?.name||({day:'My day',work:'Work, together',spaces:'A space for every client',blueprints:'Process blueprints',tools:'Your tools',insights:'Insights',organization:'The organization'}[page])}</h1><p className="subtitle">{currentProject?.description||({day:'Pick up where you left off.',work:'Projects and the people moving them forward.',spaces:'Clients, owned platforms, and everything connected to them.',blueprints:'Understand the journey. Know what connects.',tools:'Every tool has a purpose and a place.',insights:'Understand what is happening, with evidence.',organization:'The practical things, in one shared place.'}[page])}</p></div>{['day','work'].includes(page)&&<Button className="primary-button" onClick={()=>setCreate(true)} disabled={!ready}><Plus size={16}/>New task</Button>}</div>}
 {needsSignIn&&<div className="attention-box"><span>Sign in to open your private workspace.</span><a href="/signin-with-chatgpt?return_to=%2F" target="_top">Sign in with ChatGPT →</a></div>}
 {error&&<div className="error-banner" role="alert">{error}<button onClick={()=>{setError('');void refresh().catch(e=>setError(e.message))}}>Retry</button></div>}
 {!ready&&!needsSignIn&&!error&&<div className="connection-bar"><LoaderCircle size={16} className="animate-spin"/>Opening your workspace…</div>}
 {page==='day'&&<><div className="attention-box"><div className="attention-icon"><Inbox size={18}/></div><div><strong>{pending.length?`${pending.length} ${pending.length===1?'piece':'pieces'} of work ready for your eyes`:'You’re all caught up on reviews'}</strong><p>{pending.length?'A quick review keeps the next step moving.':'Your review requests will appear here.'}</p></div>{pending.length>0&&<button onClick={()=>openTask(pending[0].id)}>Review work<ArrowRight size={15}/></button>}</div><div className="board-toolbar"><Tabs value={scope} onValueChange={v=>setScope(String(v))}><TabsList className="view-tabs"><TabsTrigger value="mine">My board</TabsTrigger><TabsTrigger value="team"><Users size={14}/>Team board</TabsTrigger></TabsList></Tabs><span className="quiet-meta">{shown.filter(t=>t.stage!=='Done').length} open tasks<span className="divider-dot">·</span>Changes stay connected</span></div>{board}</>}
 {page==='work'&&(projectId?<><button className="back-link" onClick={()=>setProjectId(null)}>← All projects</button>{board}</>:<><div className="section-toolbar"><span className="quiet-meta">Client projects and internal work</span><Button variant="outline" onClick={()=>void act({type:'template',spaceId:'nord'})} disabled={!ready||busy}><Plus size={15}/>Use campaign template</Button></div><div className="project-grid">{data.projects.map(p=>{const s=data.spaces.find(s=>s.id===p.spaceId),tasks=data.tasks.filter(t=>t.projectId===p.id),done=tasks.filter(t=>t.stage==='Done').length;return <button className="project-card" key={p.id} onClick={()=>project(p.id)}><span className="card-context"><span className="brand-dot" style={{background:s?.color||'#8491a2'}}/>{s?.name||'Internal'}</span><h2>{p.name}</h2><p>{p.description}</p><div className="progress-track"><div style={{width:tasks.length?`${done/tasks.length*100}%`:'0%'}}/></div><footer><span>{done} of {tasks.length} tasks complete</span><ArrowUpRight size={16}/></footer></button>})}</div></>)}
 {page==='spaces'&&(currentSpace?<ClientFocus key={currentSpace.id} space={currentSpace} data={data} busy={busy} ready={ready} error={error} act={act} openTask={openTask} openProject={project} back={()=>navigate('spaces')}/>:<div className="space-grid">{data.spaces.map(s=><button className="space-card" key={s.id} onClick={()=>space(s.id)} style={{'--brand-color':s.color} as CSSProperties}><div className="space-cover"><span>{s.type}</span><h2>{s.name}</h2></div><footer><span>{data.projects.filter(p=>p.spaceId===s.id).length} active projects</span><ArrowUpRight size={16}/></footer></button>)}</div>)}
 {page==='tools'&&<><div className="project-grid">{data.tools.map(t=><section key={t.id} className="surface tool-card"><span className="tool-icon"><Blocks size={22}/></span><h2>{t.name}</h2><p>{t.description}</p><button className="text-link" onClick={()=>project(t.projectId)}>{data.projects.find(p=>p.id===t.projectId)?.name}<ArrowUpRight size={14}/></button><p className="muted small-text">Owner · {data.members.find(m=>m.id===t.owner)?.name}</p><span className="status-label">URL not configured</span></section>)}</div><section className="surface integrations"><h2>Workspace connections</h2>{['Slack','Monday','Google Drive','Google Calendar','InSMS'].map(n=><div className="integration-row" key={n}><span>{n}</span><span className="muted">Not connected</span></div>)}</section></>}
 {page==='organization'&&<div className="client-columns"><section className="surface"><span className="eyebrow">PEOPLE & CULTURE</span><h2>The shared library</h2>{data.documents.map(d=><button className="resource-row" key={d.id} onClick={()=>setDocumentId(d.id)}><FileText size={18}/><span>{d.title}<small>{d.collection}</small></span><ChevronRight size={16}/></button>)}</section><section className="surface"><h2>The team</h2>{data.members.map(m=><div className="member-row" key={m.id}><Avatar member={m}/><span>{m.name}<small>{m.role}</small></span></div>)}<p className="muted small-text">Sample people. Workspace invitations come in a later milestone.</p></section></div>}
 {page==='blueprints'&&<section className="surface roadmap-surface"><Workflow size={30}/><h2>Map the systems behind the work</h2><p>The next milestone adds the saved canvas, editable connections, and documented / observed / actionable steps.</p><div className="process-preview">{['Ad','Landing page','Lead capture','InSMS','Meeting'].map((s,i)=><span key={s}>{i>0&&<ArrowRight size={16}/>}<strong>{s}</strong></span>)}</div><span className="status-label">Planned · no live monitoring</span></section>}
 {page==='insights'&&<section className="surface roadmap-surface"><ChartNoAxesCombined size={30}/><h2>Evidence starts with connected sources</h2><p>Campaign spend, lead quality, and bookings will connect back to their clients and process blueprints. Sources and reporting windows will stay visible.</p><span className="status-label">No analytics sources connected</span></section>}
 <div className="save-status" role="status" aria-live="polite">{busy?<><LoaderCircle size={13} className="animate-spin"/>Saving…</>:message?<><Check size={13}/>{message}</>:<><span className="status-dot"/>{ready?'Sample data · saved in the workspace':'Connecting to your workspace'}</>}</div></main></div>
 <Sheet open={!!currentTask} onOpenChange={open=>!open&&closeTask()}><SheetContent className="task-sheet" showCloseButton><SheetHeader><SheetTitle>Task workspace</SheetTitle><SheetDescription>Brief, work, and review in one place.</SheetDescription></SheetHeader>{error&&<div role="alert" className="error-banner">{error}</div>}{currentTask&&<TaskDetail key={currentTask.id} task={currentTask} data={data} busy={busy} act={act} openProject={project} openSpace={space}/>}</SheetContent></Sheet>
 <Dialog open={create} onOpenChange={setCreate}><DialogContent className="create-dialog"><DialogHeader><DialogTitle>Create a task</DialogTitle><DialogDescription>Capture it now. Keep the context with it.</DialogDescription></DialogHeader>{error&&<div role="alert" className="error-banner">{error}</div>}<CreateTask data={data} projectId={projectId} busy={busy} save={async fields=>{if(await act({type:'create',...fields}))setCreate(false)}}/></DialogContent></Dialog>
 <CommandDialog open={search} onOpenChange={setSearch} title="Search your workspace" description="Find tasks, projects, spaces, and documents."><CommandInput placeholder="Find anything in your workspace…"/><CommandList><CommandEmpty>No matching records.</CommandEmpty><CommandGroup heading="Tasks">{data.tasks.map(t=><CommandItem key={t.id} value={t.title+' '+t.id} onSelect={()=>{openTask(t.id);setSearch(false)}}><Circle size={16}/>{t.title}<span className="command-meta">{t.stage}</span></CommandItem>)}</CommandGroup><CommandGroup heading="Spaces">{data.spaces.map(s=><CommandItem key={s.id} onSelect={()=>{space(s.id);setSearch(false)}}><BriefcaseBusiness size={16}/>{s.name}</CommandItem>)}</CommandGroup><CommandGroup heading="Projects">{data.projects.map(p=><CommandItem key={p.id} onSelect={()=>{project(p.id);setSearch(false)}}><Layers size={16}/>{p.name}</CommandItem>)}</CommandGroup><CommandGroup heading="Documents">{data.documents.map(d=><CommandItem key={d.id} onSelect={()=>{setDocumentId(d.id);setSearch(false)}}><FileText size={16}/>{d.title}</CommandItem>)}</CommandGroup></CommandList></CommandDialog>
 <Sheet open={notices} onOpenChange={setNotices}><SheetContent className="notification-sheet"><SheetHeader><SheetTitle>Your inbox</SheetTitle><SheetDescription>Review requests and changes that need you.</SheetDescription></SheetHeader><div className="sheet-body">{data.notices.length?data.notices.map(n=><button className="notice-row" key={n.id} onClick={()=>{void act({type:'read-notice',id:n.id});setNotices(false);openTask(n.taskId)}}><Inbox size={18}/><span>{n.body}<small>{new Date(n.createdAt).toLocaleString()}</small></span>{!n.read&&<span className="status-dot"/>}</button>):<p className="muted">You’re caught up. New review requests will appear here.</p>}</div></SheetContent></Sheet>
 <Dialog open={!!doc} onOpenChange={open=>!open&&setDocumentId(null)}><DialogContent className="document-dialog"><DialogHeader><DialogTitle>{doc?.title}</DialogTitle><DialogDescription>{doc?.collection}</DialogDescription></DialogHeader><div className="document-content">{doc?.body}</div></DialogContent></Dialog>
 </SidebarProvider>;
}
function CreateTask({data,projectId,busy,save}:{data:Workspace;projectId:string|null;busy:boolean;save:(v:Record<string,string>)=>void}) {const [project,setProject]=useState(projectId||'inbox');return <form onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);save({title:String(f.get('title')),description:String(f.get('description')),projectId:project==='inbox'?'':project})}} className="edit-form"><label>What needs to happen?<Input name="title" required maxLength={180} placeholder="Give the task a clear outcome" autoFocus/></label><label>Project<Picker label="Project" value={project} onChange={setProject} items={[{value:'inbox',label:'Inbox — organize later'},...data.projects.map(p=>({value:p.id,label:p.name}))]}/></label><label>Context<Textarea name="description" placeholder="The brief, a note, or a useful starting point…" rows={4}/></label><Button type="submit" disabled={busy}>{busy?'Saving…':'Create task'}</Button></form>}
function TaskDetail({task,data,busy,act,openProject,openSpace}:{task:Task;data:Workspace;busy:boolean;act:(v:Record<string,unknown>)=>Promise<boolean>;openProject:(id:string)=>void;openSpace:(id:string)=>void}) {
 const [tab,setTab]=useState(task.stage==='Review'?'work':'brief'),[assignee,setAssignee]=useState(task.assignee),[reviewer,setReviewer]=useState(task.reviewer),[feedback,setFeedback]=useState(''),[note,setNote]=useState('');
 const project=data.projects.find(p=>p.id===task.projectId),space=data.spaces.find(s=>s.id===project?.spaceId),member=data.members.find(m=>m.id===task.assignee),reviews=data.reviews.filter(r=>r.taskId===task.id),currentReview=reviews.find(r=>r.version===task.version&&['Pending','Approved'].includes(r.decision));
 const cmd=(type:string,extra:Record<string,unknown>={})=>act({type,id:task.id,revision:task.revision,...extra});
 const save=(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const f=new FormData(e.currentTarget);void cmd('edit',{title:f.get('title'),description:f.get('description'),due:f.get('due'),blocked:f.get('blocked'),assignee,reviewer})};
 return <div className="sheet-body"><div className="task-breadcrumb">{space&&<button onClick={()=>openSpace(space.id)}>{space.name}</button>}{project&&<><ChevronRight size={12}/><button onClick={()=>openProject(project.id)}>{project.name}</button></>}</div><h2 className="task-title">{task.title}</h2><div className="task-meta"><Picker label="Task stage" value={task.stage} onChange={stage=>void cmd("move",{stage})} items={stages.map(s=>({value:s,label:s}))}/><Avatar member={member} small/><span>{member?.name}</span><span className="quiet-meta">Version {task.version||'—'}</span></div>{task.blocked&&<div className="blocked-note">Blocked · {task.blocked}</div>}<Tabs value={tab} onValueChange={v=>setTab(String(v))}><TabsList variant="line" className="detail-tabs"><TabsTrigger value="brief">Brief & context</TabsTrigger><TabsTrigger value="work">Work & review</TabsTrigger><TabsTrigger value="activity">Activity</TabsTrigger></TabsList></Tabs>
 {tab==='brief'&&<><form className="edit-form" onSubmit={save}><label>Task name<Input name="title" defaultValue={task.title} required maxLength={180}/></label><label>The brief<Textarea name="description" defaultValue={task.description} rows={7}/></label><div className="field-grid"><label>Responsible<Picker label="Responsible" value={assignee} onChange={setAssignee} items={data.members.map(m=>({value:m.id,label:m.name}))}/></label><label>Reviewer<Picker label="Reviewer" value={reviewer} onChange={setReviewer} items={data.members.map(m=>({value:m.id,label:m.name}))}/></label><label>Due date<Input name="due" type="date" defaultValue={task.due}/></label><label>Blocking reason<Input name="blocked" defaultValue={task.blocked} placeholder="Nothing blocking"/></label></div><Button type="submit" variant="outline" disabled={busy}>Save changes</Button></form><h3 className="detail-heading">Notes & decisions</h3>{data.notes.filter(n=>n.taskId===task.id).map(n=><div className="note" key={n.id}><span className="note-author">{data.members.find(m=>m.id===n.actor)?.name}<small>{new Date(n.createdAt).toLocaleDateString()}</small></span><p>{n.body}</p></div>)}<form onSubmit={async e=>{e.preventDefault();if(await cmd('note',{body:note}))setNote('')}} className="note-form"><Textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="Keep a decision or useful context with this task…" aria-label="Add a note" required/><Button type="submit" variant="outline" disabled={busy||!note.trim()}><Plus size={14}/>Add note</Button></form></>}
 {tab==='work'&&<><div className="work-heading"><h3>Deliverable</h3><span className="quiet-meta">{task.version?`Version ${task.version}`:'No version submitted'}</span></div><form className="edit-form" onSubmit={e=>{e.preventDefault();void cmd('deliverable',{body:new FormData(e.currentTarget).get('body')})}}><Textarea name="body" defaultValue={task.deliverable} rows={9} placeholder="Add the work, draft copy, or a link to the deliverable…" required aria-label="Deliverable content"/><Button variant="outline" disabled={busy} type="submit">Save deliverable</Button></form><section className="review-panel"><h3>{currentReview?.decision==='Approved'?'Approved and ready for handoff':task.stage==='Review'?'Ready for review':'When the work is ready'}</h3><p>{currentReview?.decision==='Approved'?'Approval is recorded. Delivery is a separate step.':task.stage==='Review'?'Review this version, then approve it or explain what needs to change.':'Save the deliverable, then send this version to the reviewer.'}</p>{task.stage!=='Review'&&task.stage!=='Done'&&<Button disabled={busy||!task.deliverable.trim()} onClick={()=>void cmd('submit')}><ArrowUpRight size={15}/>Submit for review</Button>}{task.stage==='Review'&&currentReview?.decision==='Pending'&&<><Textarea placeholder="Feedback or requested changes…" aria-label="Review feedback" value={feedback} onChange={e=>setFeedback(e.target.value)}/><div className="review-actions"><Button disabled={busy} onClick={()=>void cmd('review',{decision:'Approved',feedback})}><Check size={15}/>Approve version</Button><Button variant="outline" disabled={busy||!feedback.trim()} onClick={()=>void cmd('review',{decision:'Changes requested',feedback})}>Request changes</Button></div></>}{currentReview?.decision==='Approved'&&task.stage!=='Done'&&<><span className="status-label">External delivery · not configured</span><Button variant="outline" disabled={busy} onClick={()=>void cmd('complete')}>Complete internal work</Button></>}{task.stage==='Done'&&<span className="status-label">Completed · {task.delivery}</span>}</section>{reviews.length>0&&<><h3 className="detail-heading">Review history</h3>{reviews.map(r=><div className="note" key={r.id}><span className="note-author">Version {r.version}<small>{r.decision}</small></span>{r.feedback&&<p>{r.feedback}</p>}</div>)}</>}</>}
 {tab==='activity'&&<div className="activity-list">{data.activities.filter(a=>a.taskId===task.id).length?data.activities.filter(a=>a.taskId===task.id).map(a=><div className="activity" key={a.id}><span className="activity-dot"/><div><p>{a.body}</p><small>{data.members.find(m=>m.id===a.actor)?.name} · {new Date(a.createdAt).toLocaleString()}</small></div></div>):<p className="muted">Changes to this task will appear here, with the person and time.</p>}</div>}
 </div>;
}


