import { mutateClient } from './client-store';
import { env } from 'cloudflare:workers';
import { getChatGPTUser } from '@/app/chatgpt-auth';
import { initialWorkspace, type Workspace, type Task } from './model';
import { AppError, textValue, revisionValue, stageValue, canSubmit, dateValue } from './validation';

const collections=['members','spaces','projects','tasks','notes','activities','reviews','notices','tools','documents','meetings','spaceEvents'] as const;
type Table=typeof collections[number];
export type Context={org:string;actor:string;name:string;db:D1Database};
type DataRow=Record<string,string|number|null>;
function insert(db:D1Database,table:Table,org:string,row:object,guard?:{id:string;nonce:string}) {const fields=['org',...Object.keys(row)],values=[org,...Object.values(row)];const sql=`INSERT OR IGNORE INTO "${table}" (${fields.map(k=>`"${k}"`).join(',')}) ${guard?`SELECT ${fields.map(()=>'?').join(',')} WHERE EXISTS (SELECT 1 FROM tasks WHERE org=? AND id=? AND lastMutation=?)`:`VALUES (${fields.map(()=>'?').join(',')})`}`;return db.prepare(sql).bind(...values,...(guard?[org,guard.id,guard.nonce]:[]))}
export async function context():Promise<Context>{let user=await getChatGPTUser();if(!user&&import.meta.env.DEV)user={userId:'local-studio-owner',displayName:'Gabri',email:'local@example.invalid',fullName:'Gabri'};if(!user)throw new AppError('Sign in to access your workspace.',401);if(!env.DB)throw new AppError('The workspace database is unavailable.',503);const c={org:user.userId,actor:'me',name:user.fullName||user.displayName.split('@')[0],db:env.DB};await seed(c);return c}
async function seed(c:Context){if(await c.db.prepare('SELECT id FROM organizations WHERE id=?').bind(c.org).first())return;const data=initialWorkspace();data.members[0].name=c.name;const statements:D1PreparedStatement[]=[c.db.prepare('INSERT OR IGNORE INTO organizations (id,name,createdAt) VALUES (?,?,?)').bind(c.org,'Studio workspace',new Date().toISOString())];for(const table of collections){for(const row of data[table]){const extra=table==='reviews'?{snapshot:data.tasks.find(t=>t.id===(row as {taskId:string}).taskId)?.deliverable||''}:{};statements.push(insert(c.db,table,c.org,{...row,...extra} as DataRow))}}await c.db.batch(statements)}
export async function readWorkspace(c:Context):Promise<Workspace>{const results=await c.db.batch(collections.map(table=>c.db.prepare(`SELECT * FROM "${table}" WHERE org=?${['activities','notes','notices','reviews','spaceEvents'].includes(table)?' ORDER BY createdAt DESC':''}`).bind(c.org)));const out:Record<string,unknown>={currentMember:c.actor,demo:true};collections.forEach((table,i)=>out[table]=results[i].results.map(raw=>{const row=raw as Record<string,unknown>;const {org,lastMutation,...record}=row;void org;void lastMutation;return record}));return out as Workspace}
async function exists(c:Context,table:Table,id:string){if(!await c.db.prepare(`SELECT id FROM "${table}" WHERE org=? AND id=?`).bind(c.org,id).first())throw new AppError(`The selected ${table} record does not exist.`,404)}
function newTask(id:string,title:string,description:string,projectId:string|null,position:number):Task{return {id,title,description,projectId,assignee:'me',reviewer:'me',stage:'Up next',due:'',priority:'Normal',blocked:'',deliverable:'',delivery:'Not configured',version:0,revision:0,position,updatedAt:new Date().toISOString(),meetingId:null}}
export async function mutate(c:Context,input:Record<string,unknown>){const type=textValue(input.type,'Action',40,true),now=new Date().toISOString(),nonce=crypto.randomUUID();
 if(type.startsWith('client-')||type.startsWith('meeting-')){await mutateClient(c,input);return}
 if(type==='create'){const title=textValue(input.title,'Task name',180,true),description=textValue(input.description??'','Description'),projectId=textValue(input.projectId??'','Project',100)||null;if(projectId)await exists(c,'projects',projectId);const count=await c.db.prepare('SELECT COALESCE(MAX(position),0)+1 AS position FROM tasks WHERE org=?').bind(c.org).first<{position:number}>();const t=newTask(nonce,title,description,projectId,count?.position||1);t.due=dateValue(input.due??'');t.assignee=textValue(input.assignee??c.actor,'Responsible person',100,true);await exists(c,'members',t.assignee);const meetingId=textValue(input.meetingId??'','Meeting',100)||null;if(meetingId){const meeting=await c.db.prepare('SELECT spaceId FROM meetings WHERE org=? AND id=?').bind(c.org,meetingId).first<{spaceId:string}>();if(!meeting)throw new AppError('Meeting not found.',404);const project=projectId?await c.db.prepare('SELECT spaceId FROM projects WHERE org=? AND id=?').bind(c.org,projectId).first<{spaceId:string}>():null;if(!project||project.spaceId!==meeting.spaceId)throw new AppError('Choose a project belonging to this meeting’s client.');t.meetingId=meetingId;}await c.db.batch([insert(c.db,'tasks',c.org,t),insert(c.db,'activities',c.org,{id:crypto.randomUUID(),taskId:t.id,body:'Created the task',actor:c.actor,createdAt:now})]);return}
 if(type==='template'){const spaceId=textValue(input.spaceId,'Space',100,true);await exists(c,'spaces',spaceId);const p={id:nonce,name:'New campaign',spaceId,description:'Campaign template · brief, production, and review.',due:''};const taskNames=['Confirm the campaign brief','Create the campaign deliverables','Prepare the campaign handoff'];await c.db.batch([insert(c.db,'projects',c.org,p),...taskNames.map((name,i)=>insert(c.db,'tasks',c.org,newTask(crypto.randomUUID(),name,'Define the expected outcome and acceptance criteria.',p.id,100+i)))]);return}
 const id=textValue(input.id,'Record',100,true);
 if(type==='read-notice'){await c.db.prepare('UPDATE notices SET read=1 WHERE org=? AND id=? AND recipient=?').bind(c.org,id,c.actor).run();return}
 const task=await c.db.prepare('SELECT * FROM tasks WHERE org=? AND id=?').bind(c.org,id).first<Task>();if(!task)throw new AppError('Task not found.',404);
 if(type==='note'){const body=textValue(input.body,'Note',10000,true);await c.db.batch([insert(c.db,'notes',c.org,{id:nonce,taskId:id,body,actor:c.actor,createdAt:now}),insert(c.db,'activities',c.org,{id:crypto.randomUUID(),taskId:id,body:'Added a note',actor:c.actor,createdAt:now})]);return}
 const revision=revisionValue(input.revision);if(task.revision!==revision)throw new AppError('This task changed in another session. Close and reopen it to get the latest version.',409);
 const updates:DataRow={revision:revision+1,updatedAt:now,lastMutation:nonce};let activity='Updated task';const secondary:D1PreparedStatement[]=[];const guard={id,nonce};
 const guardSql='EXISTS (SELECT 1 FROM tasks WHERE org=? AND id=? AND lastMutation=?)';
 const invalidate=()=>secondary.push(c.db.prepare(`UPDATE reviews SET decision='Superseded' WHERE org=? AND taskId=? AND decision IN ('Pending','Approved') AND ${guardSql}`).bind(c.org,id,c.org,id,nonce));
 const notify=(recipient:string,body:string)=>secondary.push(insert(c.db,'notices',c.org,{id:crypto.randomUUID(),taskId:id,recipient,body,read:0,createdAt:now},guard));
 const submit=()=>{canSubmit(task);updates.stage='Review';updates.version=task.version+1;updates.delivery='Not configured';activity=`Submitted version ${task.version+1} for review`;invalidate();secondary.push(insert(c.db,'reviews',c.org,{id:crypto.randomUUID(),taskId:id,version:task.version+1,reviewer:task.reviewer,decision:'Pending',feedback:'',snapshot:task.deliverable,createdAt:now},guard));notify(task.reviewer,`Ready for review: ${task.title}`)};
 const complete=async()=>{const approved=await c.db.prepare("SELECT id FROM reviews WHERE org=? AND taskId=? AND version=? AND decision='Approved'").bind(c.org,id,task.version).first();if(!approved)throw new AppError('Approve the current deliverable in Work & review before completing the task.');if(task.stage==='Done')throw new AppError('The task is already complete.');updates.stage='Done';updates.delivery='Internal completion';activity='Completed internal work; no external delivery was sent'};
 if(type==='deadline'){updates.due=dateValue(input.due);activity=updates.due?'Set the deadline to '+updates.due:'Cleared the deadline'}
 else if(type==='edit'){updates.title=textValue(input.title,'Task name',180,true);updates.description=textValue(input.description,'Description');updates.due=dateValue(input.due);updates.blocked=textValue(input.blocked,'Blocking reason',500);updates.assignee=textValue(input.assignee,'Responsible person',100,true);updates.reviewer=textValue(input.reviewer,'Reviewer',100,true);await exists(c,'members',String(updates.assignee));await exists(c,'members',String(updates.reviewer));if(task.reviewer!==updates.reviewer&&task.stage==='Review'){invalidate();updates.stage='Doing'}activity='Updated the brief and task details'}
 else if(type==='move'){const stage=stageValue(input.stage);if(stage===task.stage)return;if(stage==='Review')submit();else if(stage==='Done')await complete();else{updates.stage=stage;if(task.stage==='Review'||task.stage==='Done'){invalidate();updates.delivery='Not configured'}activity=`Moved from ${task.stage} to ${stage}`}}
 else if(type==='deliverable'){if(task.stage==='Done')throw new AppError('Reopen the task before changing its deliverable.');updates.deliverable=textValue(input.body,'Deliverable',30000,true);updates.stage=task.stage==='Review'?'Doing':task.stage;updates.delivery='Not configured';invalidate();activity='Saved the deliverable draft; a new review is required'}
 else if(type==='submit')submit();
 else if(type==='review'){const decision=textValue(input.decision,'Decision',30,true);if(!['Approved','Changes requested'].includes(decision))throw new AppError('Choose an approval or changes requested.');if(task.stage!=='Review')throw new AppError('This task is not in review.');const pending=await c.db.prepare("SELECT id FROM reviews WHERE org=? AND taskId=? AND version=? AND decision='Pending'").bind(c.org,id,task.version).first<{id:string}>();if(!pending)throw new AppError('This version has already been reviewed.',409);const feedback=textValue(input.feedback??'','Feedback',10000,decision==='Changes requested');secondary.push(c.db.prepare(`UPDATE reviews SET decision=?,feedback=? WHERE org=? AND id=? AND decision='Pending' AND ${guardSql}`).bind(decision,feedback,c.org,pending.id,c.org,id,nonce));updates.stage=decision==='Approved'?'Review':'Doing';activity=`${decision} for version ${task.version}`;notify(task.assignee,`${decision}: ${task.title}`)}
 else if(type==='complete')await complete();else throw new AppError('Unknown action.');
 const fields=Object.keys(updates);const update=c.db.prepare(`UPDATE tasks SET ${fields.map(k=>`"${k}"=?`).join(',')} WHERE org=? AND id=? AND revision=?`).bind(...Object.values(updates),c.org,id,revision);
 const result=await c.db.batch([update,...secondary,insert(c.db,'activities',c.org,{id:crypto.randomUUID(),taskId:id,body:activity,actor:c.actor,createdAt:now},guard)]);if(!result[0].meta.changes)throw new AppError('This task changed in another session. Close and reopen it to refresh.',409);
}


